version: '3.4'

services:
  SqlServerDb:
        container_name: SqlServerContainer
        image: mcr.microsoft.com/mssql/server:2019-latest
        ports:
            - 8002:1433
        environment:
            - ACCEPT_EULA=Y
            - MSSQL_SA_PASSWORD=TunetCom2024 

  tunnetcom.aiontime.timelogservice.api:
    image: ${DOCKER_REGISTRY-}tunnetcomaiontimetimelogserviceapi
    build:
      context: .
      dockerfile: src/TunNetCom.AionTime.TimeLogService/TunNetCom.AionTime.TimeLogService.Budget.API/Dockerfile
    environment:
        loki: http://loki:3100
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: https://+:443;http://+:80
    ports:
        - 8085:80
        - 8086:443
    depends_on: 
        - SqlServerDb
        - loki 
  tunnetcom.aiontime.azuredevopsservice.api:
    image: ${DOCKER_REGISTRY-}tunnetcomaiontimeazuredevopsserviceapi
    build:
      context: .
      dockerfile: src/TunNetCom.AionTime.AzureDevopsService/TunNetCom.AionTime.AzureDevopsService.API/Dockerfile
    environment:
        loki: http://loki:3100
        ASPNETCORE_ENVIRONMENT: Development
        ASPNETCORE_URLS: https://+:443;http://+:80
    ports:
        - 8090:80
        - 8091:443
    depends_on: 
            loki : 
             condition: service_healthy


  loki:
    container_name: loki
    image: grafana/loki:master
    ports:
       - 3100:3100
    command: -config.file=/etc/loki/local-config.yaml
    healthcheck:
        test: wget -q --tries=1 -O- http://localhost:3100/ready 
        interval: 3s
        timeout: 3s
        retries: 10
        start_period: 10s

  grafana:
    container_name: grafana
    image: grafana/grafana:master
    ports:
      - "3000:3000"
    depends_on:
        loki:
            condition: service_healthy

