name: Publish NuGet Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Restore dependencies
      run: dotnet restore src/AzureDevopsWebhookService/AzureDevopsWebhookService.Contracts/AzureDevopsWebhookService.Contracts.csproj

    - name: Build Project
      run: dotnet build src/AzureDevopsWebhookService/AzureDevopsWebhookService.Contracts/AzureDevopsWebhookService.Contracts.csproj --configuration Release --no-restore

    - name: Pack NuGet Package
      run: dotnet pack src/AzureDevopsWebhookService/AzureDevopsWebhookService.Contracts/AzureDevopsWebhookService.Contracts.csproj --configuration Release --output ./artifacts

    - name: Publish NuGet Package
      run: dotnet nuget push "./artifacts/*.nupkg" --api-key oy2ek6igpprxblmhvvqarrhllq2t7l7e3akj4pg72abkba --source "https://api.nuget.org/v3/index.json"
