name: Publish NuGet Package

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v3

    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: '8.x'

    - name: Find Project Paths
      id: find-projects
      run: |
        echo "##[group]Finding .csproj paths"
        PROJECT_PATHS=$(find . -name "WebhookService.Contracts.csproj" -o -name "AzureDevopsService.Contracts.csproj" | tr '\n' ' ')
        echo "Found projects: $PROJECT_PATHS"
        echo "##[endgroup]"
        echo "PROJECT_PATHS=$PROJECT_PATHS" >> $GITHUB_ENV

    - name: Restore dependencies
      run: |
        for project in ${{ env.PROJECT_PATHS }}; do
          dotnet restore $project
        done

    - name: Build Projects
      run: |
        for project in ${{ env.PROJECT_PATHS }}; do
          dotnet build $project --configuration Release --no-restore
        done

    - name: Pack NuGet Packages
      run: |
        for project in ${{ env.PROJECT_PATHS }}; do
          dotnet pack $project --configuration Release --output ./artifacts
        done

    - name: Publish NuGet Packages
      run: dotnet nuget push "./artifacts/*.nupkg" --api-key ${{ secrets.NUGET_SECRET_KEY_TUNNETCOM }} --source "https://api.nuget.org/v3/index.json"
