global:
  scrape_interval:     10s
  evaluation_interval: 10s

scrape_configs:
  - job_name: aggregated-trace-metrics
    static_configs:
      - targets:
          - otel-collector:8889

  - job_name: jaeger
    static_configs:
      - targets:
          - jaeger:14269

  - job_name: services
    static_configs:
      - targets:
          - TimeLog_Service:80
          - Azure_Devops_Service:80
          - Azure_Devops_Webhook_Service:80
          - Azure_Devops_Identity_Service:80 